    TranslationUnitDecl_0x1979690 [shape=record,style=filled,fillcolor=lightgrey,label="{ TranslationUnitDecl| &lt;&lt;invalid&nbsp;sloc&gt;&gt;| }"];
    TypedefDecl_0x1979b70 [shape=record,style=filled,fillcolor=lightgrey,label="{ TypedefDecl| &lt;&lt;invalid&nbsp;sloc&gt;&gt;| __int128_t| '__int128'| }"];
    TypedefDecl_0x1979bd0 [shape=record,style=filled,fillcolor=lightgrey,label="{ TypedefDecl| &lt;&lt;invalid&nbsp;sloc&gt;&gt;| __uint128_t| 'unsigned| __int128'| }"];
    TypedefDecl_0x1979f20 [shape=record,style=filled,fillcolor=lightgrey,label="{ TypedefDecl| &lt;&lt;invalid&nbsp;sloc&gt;&gt;| __builtin_va_list| '__va_list_tag| [1]'| }"];
    FunctionDecl_0x197a040 [shape=record,style=filled,fillcolor=lightgrey,label="{ FunctionDecl| &lt;ex.c:1:1,&nbsp;line:10:1&gt;| foo| 'int| (int)'| }"];
    ParmVarDecl_0x1979f80 [shape=record,style=filled,fillcolor=lightgrey,label="{ ParmVarDecl| &lt;line:1:9,&nbsp;col:13&gt;| a| 'int'| }"];
    CompoundStmt_0x19a6928 [shape=record,style=filled,fillcolor=lightgrey,label="{ CompoundStmt| &lt;line:2:1,&nbsp;line:10:1&gt;| }"];
    DeclStmt_0x197a200 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclStmt| &lt;line:3:2,&nbsp;col:14&gt;| }"];
    VarDecl_0x197a100 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:2,&nbsp;col:6&gt;| b| 'int'| }"];
    VarDecl_0x197a170 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:2,&nbsp;col:13&gt;| c| 'int'| }"];
    IntegerLiteral_0x197a1c8 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:13&gt;| 'int'| 1| }"];
    BinaryOperator_0x197a2e8 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;line:5:2,&nbsp;col:10&gt;| 'int'| '='| }"];
    DeclRefExpr_0x197a218 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:2&gt;| 'int'| lvalue| Var| 0x197a100| 'b'| 'int'| }"];
    BinaryOperator_0x197a2c0 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:6,&nbsp;col:10&gt;| 'int'| '*'| }"];
    ImplicitCastExpr_0x197a290 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:6&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x197a240 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:6&gt;| 'int'| lvalue| Var| 0x197a170| 'c'| 'int'| }"];
    ImplicitCastExpr_0x197a2a8 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:10&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x197a268 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:10&gt;| 'int'| lvalue| ParmVar| 0x1979f80| 'a'| 'int'| }"];
    ForStmt_0x19a6888 [shape=record,style=filled,fillcolor=lightgrey,label="{ ForStmt| &lt;line:6:2,&nbsp;line:7:17&gt;| }"];
    DeclStmt_0x197a398 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclStmt| &lt;line:6:7,&nbsp;col:16&gt;| }"];
    VarDecl_0x197a320 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:7,&nbsp;col:15&gt;| n| 'int'| }"];
    IntegerLiteral_0x197a378 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:15&gt;| 'int'| 0| }"];
    NULL_0 [shape=record,style=filled,fillcolor=lightgrey,label="{ &lt;&lt;&lt;NULL_0&gt;&gt;&gt;| }"];
    BinaryOperator_0x19a6698 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:18,&nbsp;col:26&gt;| 'int'| '&lt;'| }"];
    ImplicitCastExpr_0x19a6680 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:18&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a65d0 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:18&gt;| 'int'| lvalue| Var| 0x197a320| 'n'| 'int'| }"];
    BinaryOperator_0x19a6658 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:22,&nbsp;col:26&gt;| 'int'| '+'| }"];
    ImplicitCastExpr_0x19a6640 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:22&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a65f8 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:22&gt;| 'int'| lvalue| Var| 0x197a170| 'c'| 'int'| }"];
    NULL_1 [shape=record,style=filled,fillcolor=lightgrey,label="{ &lt;&lt;&lt;NULL_1&gt;&gt;&gt;| }"];
    IntegerLiteral_0x19a6620 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:26&gt;| 'int'| 5| }"];
    UnaryOperator_0x19a66e8 [shape=record,style=filled,fillcolor=lightgrey,label="{ UnaryOperator| &lt;col:29,&nbsp;col:30&gt;| 'int'| postfix| '++'| }"];
    NULL_2 [shape=record,style=filled,fillcolor=lightgrey,label="{ &lt;&lt;&lt;NULL_2&gt;&gt;&gt;| }"];
    DeclRefExpr_0x19a66c0 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:29&gt;| 'int'| lvalue| Var| 0x197a320| 'n'| 'int'| }"];
    BinaryOperator_0x19a6860 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;line:7:3,&nbsp;col:17&gt;| 'int'| '='| }"];
    DeclRefExpr_0x19a6708 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:3&gt;| 'int'| lvalue| Var| 0x197a100| 'b'| 'int'| }"];
    BinaryOperator_0x19a6838 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:7,&nbsp;col:17&gt;| 'int'| '+'| }"];
    ImplicitCastExpr_0x19a6820 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:7&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a6730 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:7&gt;| 'int'| lvalue| Var| 0x197a100| 'b'| 'int'| }"];
    ParenExpr_0x19a6800 [shape=record,style=filled,fillcolor=lightgrey,label="{ ParenExpr| &lt;col:11,&nbsp;col:17&gt;| 'int'| }"];
    BinaryOperator_0x19a67d8 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:12,&nbsp;col:16&gt;| 'int'| '*'| }"];
    ImplicitCastExpr_0x19a67a8 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:12&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a6758 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:12&gt;| 'int'| lvalue| Var| 0x197a320| 'n'| 'int'| }"];
    ImplicitCastExpr_0x19a67c0 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:16&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a6780 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:16&gt;| 'int'| lvalue| ParmVar| 0x1979f80| 'a'| 'int'| }"];
    ReturnStmt_0x19a6908 [shape=record,style=filled,fillcolor=lightgrey,label="{ ReturnStmt| &lt;line:9:2,&nbsp;col:9&gt;| }"];
    ImplicitCastExpr_0x19a68f0 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:9&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a68c8 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:9&gt;| 'int'| lvalue| Var| 0x197a100| 'b'| 'int'| }"];
    FunctionDecl_0x19a6b50 [shape=record,style=filled,fillcolor=lightgrey,label="{ FunctionDecl| &lt;line:12:1,&nbsp;line:20:1&gt;| main| 'int| (int,| char| **)'| }"];
    ParmVarDecl_0x19a6970 [shape=record,style=filled,fillcolor=lightgrey,label="{ ParmVarDecl| &lt;line:13:6,&nbsp;col:10&gt;| argc| 'int'| }"];
    ParmVarDecl_0x19a6a80 [shape=record,style=filled,fillcolor=lightgrey,label="{ ParmVarDecl| &lt;col:16,&nbsp;col:27&gt;| argv| 'char| **'| }"];
    CompoundStmt_0x19a70b0 [shape=record,style=filled,fillcolor=lightgrey,label="{ CompoundStmt| &lt;line:14:1,&nbsp;line:20:1&gt;| }"];
    DeclStmt_0x19a6d20 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclStmt| &lt;line:15:2,&nbsp;col:17&gt;| }"];
    VarDecl_0x19a6c10 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:2,&nbsp;col:16&gt;| v1| 'int'| }"];
    CallExpr_0x19a6cf0 [shape=record,style=filled,fillcolor=lightgrey,label="{ CallExpr| &lt;col:11,&nbsp;col:16&gt;| 'int'| }"];
    ImplicitCastExpr_0x19a6cd8 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:11&gt;| 'int| (*)(int)'| &lt;FunctionToPointerDecay&gt;| }"];
    DeclRefExpr_0x19a6c68 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:11&gt;| 'int| (int)'| Function| 0x197a040| 'foo'| 'int| (int)'| }"];
    IntegerLiteral_0x19a6c90 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:15&gt;| 'int'| 1| }"];
    DeclStmt_0x19a6e38 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclStmt| &lt;line:16:2,&nbsp;col:17&gt;| }"];
    VarDecl_0x19a6d50 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:2,&nbsp;col:16&gt;| v2| 'int'| }"];
    CallExpr_0x19a6e08 [shape=record,style=filled,fillcolor=lightgrey,label="{ CallExpr| &lt;col:11,&nbsp;col:16&gt;| 'int'| }"];
    ImplicitCastExpr_0x19a6df0 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:11&gt;| 'int| (*)(int)'| &lt;FunctionToPointerDecay&gt;| }"];
    DeclRefExpr_0x19a6da8 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:11&gt;| 'int| (int)'| Function| 0x197a040| 'foo'| 'int| (int)'| }"];
    IntegerLiteral_0x19a6dd0 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:15&gt;| 'int'| 2| }"];
    DeclStmt_0x19a6f48 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclStmt| &lt;line:17:2,&nbsp;col:17&gt;| }"];
    VarDecl_0x19a6e60 [shape=record,style=filled,fillcolor=lightgrey,label="{ VarDecl| &lt;col:2,&nbsp;col:16&gt;| v3| 'int'| }"];
    CallExpr_0x19a6f18 [shape=record,style=filled,fillcolor=lightgrey,label="{ CallExpr| &lt;col:11,&nbsp;col:16&gt;| 'int'| }"];
    ImplicitCastExpr_0x19a6f00 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:11&gt;| 'int| (*)(int)'| &lt;FunctionToPointerDecay&gt;| }"];
    DeclRefExpr_0x19a6eb8 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:11&gt;| 'int| (int)'| Function| 0x197a040| 'foo'| 'int| (int)'| }"];
    IntegerLiteral_0x19a6ee0 [shape=record,style=filled,fillcolor=lightgrey,label="{ IntegerLiteral| &lt;col:15&gt;| 'int'| 4| }"];
    ReturnStmt_0x19a7090 [shape=record,style=filled,fillcolor=lightgrey,label="{ ReturnStmt| &lt;line:19:2,&nbsp;col:22&gt;| }"];
    ParenExpr_0x19a7070 [shape=record,style=filled,fillcolor=lightgrey,label="{ ParenExpr| &lt;col:9,&nbsp;col:22&gt;| 'int'| }"];
    BinaryOperator_0x19a7048 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:10,&nbsp;col:20&gt;| 'int'| '+'| }"];
    BinaryOperator_0x19a6fe0 [shape=record,style=filled,fillcolor=lightgrey,label="{ BinaryOperator| &lt;col:10,&nbsp;col:15&gt;| 'int'| '+'| }"];
    ImplicitCastExpr_0x19a6fb0 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:10&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a6f60 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:10&gt;| 'int'| lvalue| Var| 0x19a6c10| 'v1'| 'int'| }"];
    ImplicitCastExpr_0x19a6fc8 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:15&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a6f88 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:15&gt;| 'int'| lvalue| Var| 0x19a6d50| 'v2'| 'int'| }"];
    ImplicitCastExpr_0x19a7030 [shape=record,style=filled,fillcolor=lightgrey,label="{ ImplicitCastExpr| &lt;col:20&gt;| 'int'| &lt;LValueToRValue&gt;| }"];
    DeclRefExpr_0x19a7008 [shape=record,style=filled,fillcolor=lightgrey,label="{ DeclRefExpr| &lt;col:20&gt;| 'int'| lvalue| Var| 0x19a6e60| 'v3'| 'int'| }"];
